### ISSUE TITLE
libotclient.so crash

### ISSUE THREAD

**Issue by KoukiShichirou** [edubart/otclient#735]
I followed tutorial, also put the SDL lib into /lib folder, my apk have 375kB in size, here it is:
[OTClient-debug.zip](https://github.com/edubart/otclient/files/286936/OTClient-debug.zip)

```
--------- beginning of crash
E/AndroidRuntime(11311): FATAL EXCEPTION: main
E/AndroidRuntime(11311): Process: com.otclient.mobile, PID: 11311
E/AndroidRuntime(11311): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.otclient.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/com.otclient.mobile-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libotclient.so"
E/AndroidRuntime(11311):        at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(11311):        at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(11311):        at com.otclient.mobile.MainActivity.<clinit>(MainActivity.java:22)
E/AndroidRuntime(11311):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(11311):        at java.lang.Class.newInstance(Class.java:1606)
E/AndroidRuntime(11311):        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
E/AndroidRuntime(11311):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
E/AndroidRuntime(11311):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime(11311):        at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(11311):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(11311):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11311):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11311):        at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(11311):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11311):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11311):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(11311):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/ActivityManager(  907):   Force finishing activity 1 com.otclient.mobile/.MainActivity
```

**Comment by KoukiShichirou** [comment]
http://pastebin.com/78PZajs3
There is an linking error, tutorial is not working anymore.

**Comment by Tulioh** [comment]
You are missing boost libraries in one of these steps and the otclient is
not compiling.

2016-05-27 13:46 GMT-03:00 KoukiShichirou <notifications@github.com>:

**Comment by KoukiShichirou** [comment]
Ok, it's working now. I have problems because 

> C:/Users/Kouki/Android-Dev/android-ndk-r11c/libraries/lib/libcrypto.a(ui_openssl.c.o):ui_openssl.c:function signal: error: undefined reference to 'bsd_signal'

New Android api changed bsd_signal to signal, I download now old version, will give a try.

**Comment by Tulioh** [comment]
Try the version that is specified in the tutorial.

2016-05-27 16:56 GMT-03:00 KoukiShichirou <notifications@github.com>:

**Comment by KoukiShichirou** [comment]
It's working actually, I can't login because of networking bug (that one what Szybol7 reported), I hope that someone will develop more this client (maybe me?).
Pretty much compiled .apk with OTClient resources (which must be placed under /sdcard) are placed on my blog:
http://www.kouki-shichirou.pl/index.php/posts/otclient-alternative-tibia-apk-download
